version: '3.9'

services:
  # Наш AI Бот
  ai_agent:
    build: .
    container_name: ai_agent_bot
    restart: always
    env_file:
      - .env
    # Мы убрали ports "8000:8000", теперь бот доступен ТОЛЬКО внутри Docker сети.
    # Снаружи к нему не подключиться — это безопасно.
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
      
  # 4. Portainer (Визуальный мониторинг)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: monitoring_portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

volumes:
  portainer_data: